name: matador@linux

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - .github/workflows/windows.yml
      - .github/workflows/release.yml
      - appveyor.yml
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/windows.yml
      - .github/workflows/release.yml
      - appveyor.yml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [12]
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          SA_PASSWORD: Password12!
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password12!' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Create MySQL database
      run: |
        sudo systemctl start mysql.service
        mysql --version
        mysql -u root -proot -e "CREATE DATABASE matador_test;"
    - name: Create MS SQL Database
      run: |
        sudo apt-get update && sudo apt-get install -y mssql-tools
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password12!' -Q 'CREATE DATABASE matador_test'
    - name: Check ODBC
      run: |
        odbcinst -j
        cat /etc/odbcinst.ini
        cat /etc/odbc.ini
    - name: CMake Version
      run: cmake --version
    - name: Configure CMake
      env:
        CC: gcc-${{ matrix.compiler-version }}
        CXX: g++-${{ matrix.compiler-version }}
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DMSSQL_CONNECTION_STRING:STRING="mssql://sa:Password12!@127.0.0.1/matador_test (ODBC Driver 17 for SQL Server)"
        -DMATADOR_ODBC_TEST=true
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target matador test_matador
    - name: Copy Matador Libs
      working-directory: ${{github.workspace}}/build
      run: |
        ls -la lib/libmatador-*.*
        cp lib/libmatador-*.* bin/
        pwd
        ls -la bin/
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'
        postgresql db: matador_test
        postgresql user: test
        postgresql password: test123
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ls -la bin/
        ctest --verbose -C ${{env.BUILD_TYPE}}
