name: matador@linux

on:
  push:
    branches:
      - develop
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_HOST: 127.0.0.1
#          MYSQL_DB: matador_test
#          MYSQL_USER: root
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
#          MYSQL_PASSWORD:
#        ports:
#          - "3306:3306"
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [9]
    steps:
    - uses: actions/checkout@v2
    - name: CMake Version
      run: cmake --version
    - name: Configure CMake
      env:
        CC: gcc-${{ matrix.compiler-version }}
        CXX: g++-${{ matrix.compiler-version }}
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DMATADOR_ODBC_TEST=false
        -DMATADOR_POSTGRESQL_TEST=true
        -DMATADOR_MYSQL_TEST=true
        -DMATADOR_SQLITE3_TEST=true
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Copy Matador Libs
      working-directory: ${{github.workspace}}/build
      run: cp lib/libmatador-*.* bin/
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: matador_test
        postgresql user: test
        postgresql password: test123
    - name: Shutdown the Default MySQL
      run: sudo systemctl start mysql.service
#    - uses: mirromutth/mysql-action@v1.1
#      with:
#        mysql database: 'matador_test'
#        mysql root password: 'root123'
#        mysql user: 'test'
#        mysql password: 'test123'
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose -C ${{env.BUILD_TYPE}}

