name: matador@linux

on:
  push:
    branches:
      - develop
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [9]
    steps:
    - uses: actions/checkout@v2
    - name: CMake Version
      run: cmake --version
    - name: Configure CMake
      env:
        CC: gcc-${{ matrix.compiler-version }}
        CXX: g++-${{ matrix.compiler-version }}
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DMATADOR_ODBC_TEST=false
        -DMATADOR_POSTGRESQL_TEST=false
        -DMATADOR_MYSQL_TEST=false
        -DMATADOR_SQLITE3_TEST=true
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: List libs
      run: ls -la ${{github.workspace}}/build/lib
#    - name: Copy Matador SQlite libs
#      working-directory: ${{github.workspace}}/build
#      run: cp lib/libmatador-sqlite.* bin/
    - name: List bin
      run: ls -la ${{github.workspace}}/build/bin
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose -C ${{env.BUILD_TYPE}}

