name: matador@linux:release

on:
  push:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/windows.yml
      - .github/workflows/linux.yml
      - .github/workflows/coverage.yml
      - appveyor.yml
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/windows.yml
      - .github/workflows/linux.yml
      - .github/workflows/coverage.yml
      - appveyor.yml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [9]
    steps:
      - name: Install Doxygen
        run: |
          sudo apt-get -y install doxygen
          which doxygen
      - name: Set version name
        id: version
        run: echo ::set-output name=name::6.6.6
        #run: echo ::set-output name=name::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - name: CMake Version
        run: cmake --version
      - name: Configure CMake
        env:
          CC: gcc-${{ matrix.compiler-version }}
          CXX: g++-${{ matrix.compiler-version }}
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DMATADOR_ODBC_TEST=false
          -DMATADOR_ODBC=true
          -DMATADOR_POSTGRESQL_TEST=true
          -DMATADOR_MYSQL_TEST=true
          -DMATADOR_SQLITE3_TEST=true
          -DCOVERAGE=false
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target matador
      - name: Copy Matador Libs
        working-directory: ${{github.workspace}}/build
        run: cp lib/libmatador-*.* bin/
      - name: Build Documentation
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --target web
      - name: Build Packges
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --target package
      - name: List Packages
        working-directory: ${{github.workspace}}/Package
        run: ls -la
      - name: Upload Debian Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: matador-${{ steps.version.outputs.name }}-x86_64-${{ runner.os }}.deb
          path: ${{github.workspace}}/Package/matador*.deb
      - name: Upload RPM Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: matador-${{ steps.version.outputs.name }}-x86_64-${{ runner.os }}.rpm
          path: ${{github.workspace}}/Package/matador*.rpm
      - name: Upload TGZ Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: matador-${{ steps.version.outputs.name }}-x86_64-${{ runner.os }}.tar.gz
          path: ${{github.workspace}}/Package/matador*.tar.gz
