name: matador@windows

on:
  push:
    branches:
      - develop
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  INSTALL_LOCATION: ".local"

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{env.INSTALL_LOCATION}}
          key: ${{runner.os}}-dependencies
      - name: Start PostgreSQL
        run: |
          $pgService = Get-Service -Name postgresql*
          Set-Service -InputObject $pgService -Status running -StartupType automatic
          Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
      - name: Create PostgreSQL User
        run: |
          & $env:PGBIN\psql --command="CREATE USER test PASSWORD 'test123'" --command="\du"
      - name: Create PostgreSQL TestDB
        run: |
          & $env:PGBIN\createdb --owner=test matador_test
          $env:PGPASSWORD = 'test123'
          & $env:PGBIN\psql --username=test --host=localhost --list matador_test
      - uses: ankane/setup-mysql@v1
        with:
          database: matador_test
      - run: mysql -D matador_test -e 'SELECT VERSION()'
      - name: CMake Version
        run: cmake --version
      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION"
          -DMATADOR_ODBC_TEST=false
          -DMATADOR_ODBC=false
          -DMATADOR_POSTGRESQL_TEST=true
          -DMATADOR_MYSQL_TEST=false
          -DMATADOR_SQLITE3_TEST=false
      - name: Build
        run: >
          cmake --build ${{github.workspace}}/build
          --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C ${{env.BUILD_TYPE}}
