name: matador@windows

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/release.yml
      - .github/workflows/coverage.yml
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/release.yml
      - .github/workflows/coverage.yml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{env.INSTALL_LOCATION}}
          key: ${{runner.os}}-dependencies
      - name: Start PostgreSQL
        run: |
          $pgService = Get-Service -Name postgresql*
          Set-Service -InputObject $pgService -Status running -StartupType automatic
          Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
      - name: Create PostgreSQL User
        run: |
          & $env:PGBIN\psql --command="CREATE USER test PASSWORD 'test123'" --command="\du"
      - name: Create PostgreSQL TestDB
        run: |
          & $env:PGBIN\createdb --owner=test matador_test
          $env:PGPASSWORD = 'test123'
          & $env:PGBIN\psql --username=test --host=localhost --list matador_test
      - name: Install SQLite
        shell: cmd
        run: |
          choco install sqlite
          cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib
          mkdir lib
          copy sqlite3.* lib\
          dir lib
      - name: Install SQLite Header
        shell: cmd
        run: |
          cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
          curl -L https://www.sqlite.org/2021/sqlite-amalgamation-3360000.zip --output sqlite-amalgamation-3360000.zip
          7z x sqlite-amalgamation-3360000.zip
          mkdir include
          copy sqlite-amalgamation-3360000\sqlite3*.h include\
          dir include
      - name: Set variables for SQLite
        shell: bash
        run: |
          echo "C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_PATH
          echo "SQLITE3_DIR=C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_ENV
      - name: Install mysql
        shell: cmd
        run: choco install mysql
      - name: Prepare MySQL
        shell: cmd
        run: |
          "C:\tools\mysql\current\bin\mysql" -u root -e "create database matador_test;"
          "C:\tools\mysql\current\bin\mysql" -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123'"
          "C:\tools\mysql\current\bin\mysql" -u root -e "GRANT ALL PRIVILEGES ON matador_test.* TO 'test'@'localhost'"
          "C:\tools\mysql\current\bin\mysql" -u root -e "FLUSH PRIVILEGES"
          "C:\tools\mysql\current\bin\mysql" -u root -e "SHOW GRANTS FOR 'test'@'localhost'"
      - name: Set MySQL variables
        shell: bash
        run: |
          echo "MYSQL_DIR=C:\tools\mysql\current" >> $GITHUB_ENV
      - name: MySQL checks
        shell: cmd
        run: |
          cd /D C:\tools\mysql\current
          dir
          dir include
          dir lib
      - name: CMake Version
        run: cmake --version
      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION"
          -DMYSQL_LIBRARY="${{env.MYSQL_DIR}}\lib\libmysql.lib"
          -DMYSQL_INCLUDE_DIR="${{env.MYSQL_DIR}}\include"
          -DMATADOR_ODBC_TEST=false
          -DMATADOR_MYSQL_TEST=false
          -DMYSQL_CONNECTION_STRING=mysql://test:test123@127.0.0.1/matador_test
      - name: Build
        run: >
          cmake --build ${{github.workspace}}/build
          --config ${{env.BUILD_TYPE}}
          --target matador test_matador
      - name: List Debug
        working-directory: ${{github.workspace}}/build/Debug/bin/Debug
        run: dir
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C ${{env.BUILD_TYPE}}
