name: matador@windows

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/release.yml
      - .github/workflows/coverage.yml
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/release.yml
      - .github/workflows/coverage.yml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{env.INSTALL_LOCATION}}
          key: ${{runner.os}}-dependencies
      - name: Start PostgreSQL
        run: |
          $pgService = Get-Service -Name postgresql*
          Set-Service -InputObject $pgService -Status running -StartupType automatic
          Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
      - name: Create PostgreSQL User
        run: |
          & $env:PGBIN\psql --command="CREATE USER test PASSWORD 'test123'" --command="\du"
      - name: Create PostgreSQL TestDB
        run: |
          & $env:PGBIN\createdb --owner=test matador_test
          $env:PGPASSWORD = 'test123'
          & $env:PGBIN\psql --username=test --host=localhost --list matador_test
      - name: Install sqlite
        shell: cmd
        run: |
          choco install sqlite
          cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib
      - name: Install mysql (Windows)
        shell: cmd
        run: |
          choco install mysql
          "C:\tools\mysql\current\bin\mysql" -u root -e "create database matador_test;"
          "C:\tools\mysql\current\bin\mysql" -D matador_test -e 'SELECT VERSION()'
          "C:\tools\mysql\current\bin\mysql" -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123'"
          "C:\tools\mysql\current\bin\mysql" -u root -e "GRANT ALL PRIVILEGES ON matador_test.* TO 'test'@'localhost'"
          "C:\tools\mysql\current\bin\mysql" -u root -e "FLUSH PRIVILEGES"
          "C:\tools\mysql\current\bin\mysql" -u root -e "SHOW GRANTS FOR 'test'@'localhost'"
      - name: CMake Version
        run: cmake --version
      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION"
          -DMATADOR_ODBC_TEST=false
          -DMYSQL_CONNECTION_STRING=mysql://test:test123@127.0.0.1/matador_test
          -DMATADOR_SQLITE3_TEST=false
          -DMATADOR_MYSQL_TEST=true
      - name: Build
        run: >
          cmake --build ${{github.workspace}}/build
          --config ${{env.BUILD_TYPE}}
          --target matador test_matador
      - name: List Debug
        working-directory: ${{github.workspace}}/build/Debug/bin/Debug
        run: dir
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C ${{env.BUILD_TYPE}}
